# Generated by Django 3.2.7 on 2021-09-19 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_auto_20210917_0436'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('msg_id_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('email', models.CharField(default='', max_length=100)),
                ('subject', models.CharField(default='', max_length=100)),
                ('desc', models.CharField(max_length=500)),
                ('pubdate', models.DateField()),
            ],
        ),
    ]
